### ISSUE TITLE
Report an function not find error of scAPA.shell.script.R

### ISSUE THREAD

**Issue by cqz7633** [ElkonLab/scAPA#11]
I got an error "could not find function write_log_start" after runing the scAPA.shell.script.R. I didn't find this function in script, and found that "write_log" were also not in the script. Is the script incomplete or these function were in some R packages i not found?

**Comment by houruiyan** [comment]
For those people who also meet this problem, 
this is because that the above error looking like this 
<img width="1440" alt="image" src="https://github.com/ElkonLab/scAPA/assets/56068158/142d8c24-a133-452d-883b-a756d846e1ca">

You should assign loc in your shell script, like this 
`(base) [ruiyanhou@CPU3:scAPA.shell.script]$ Rscript scAPA.shell.script.R -p /mnt/ruiyanhou/nfs_share2/three_primer/PBMC/run_scAPA/data/inputdata -org Hs -sp /mnt/ruiyanhou/nfs_share2/three_primer/PBMC/run_scAPA/scAPA/scAPA.shell.script -loc /home/ruiyanhou/R/x86_64-pc-linux-gnu-library/4.3`

Firstly, in R and use this command to get the path of R library 
`system.file(package = "Rsubread")`
Then add the path to the loc in Rscript
